from scrapy import cmdline

# cmdline.execute(['scrapy', 'crawl', 'FundNav_JinguTrust', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_GuangdaBank', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_WuhanWeixinFund', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_TianhesichuangInvset', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_XrzFund', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_BaoyinCyInvset', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_XZeastmoney', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_XinPuAsset', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_BotongInvset', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_HongdaoInvset', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_HowBuy', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_MingxiZichan', '-a', 'jobId=0L'])
cmdline.execute(['scrapy', 'crawl', 'FundNav_SZqhhqzb', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_ZhenxinZichan', '-a', 'jobId=0L'])
# cmdline.execute(['scrapy', 'crawl', 'FundNav_ZhejiangBkxtz', '-a', 'jobId=0L'])
